apiVersion: v2
name: cert-manager-webhook-servercore
version: 1.5.1
appVersion: "1.5.1"
kubeVersion: ">= 1.22.0-0"
description: Allow cert-manager to solve DNS challenges using Servercore DNS API
home: https://github.com/ykachube/cert-manager-webhook-servercore
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo-small.png
keywords:
  - cert-manager
  - servercore
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/ykachube/cert-manager-webhook-servercore
maintainers:
  - name: ykachube
    email: yury_kachubeyeu@gmail.com
annotations:
  artifacthub.io/license: Apache-2.0
